services:
  casplo2gpx-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    labels:
      - com.getarcaneapp.arcane.updater=false
    restart: unless-stopped
