services:
  casplo2gpx-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: casplo2gpx-web:local
    container_name: casplo2gpx-web
    ports:
      - "3000:3000"
    restart: unless-stopped
